import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { Resend } from "resend";

export async function POST(request: NextRequest) {
  const resend = new Resend(process.env.RESEND_API_KEY);
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (user.user_metadata?.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body = await request.json();
  const { email, role } = body as { email?: string; role?: string };

  if (
    !email ||
    !role ||
    !["startup", "investor", "admin"].includes(role)
  ) {
    return NextResponse.json({ error: "Invalid email or role" }, { status: 400 });
  }

  // Create the invitation row — token is generated by the DB default
  const { data: invitation, error: inviteError } = await supabase
    .from("invitations")
    .insert({ email, role, invited_by: user.id })
    .select("token")
    .single();

  if (inviteError || !invitation) {
    return NextResponse.json(
      { error: inviteError?.message ?? "Failed to create invitation" },
      { status: 500 }
    );
  }

  const inviteUrl = `https://startgrid.vercel.app/accept-invite?token=${invitation.token}`;
  const roleLabel = role.charAt(0).toUpperCase() + role.slice(1);

  const { error: emailError } = await resend.emails.send({
    // Update `from` to a verified Resend domain before going to production
    from: "StartGrid <invites@start-grid.com>",
    to: email,
    subject: `You're invited to join StartGrid`,
    html: `
      <!DOCTYPE html>
      <html>
        <body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
          <table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px;">
            <tr>
              <td align="center">
                <table width="480" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;border:1px solid #e5e7eb;padding:40px;">
                  <tr>
                    <td>
                      <h1 style="margin:0 0 4px;font-size:22px;font-weight:700;color:#18181b;">StartGrid</h1>
                      <p style="margin:0 0 32px;font-size:13px;color:#71717a;">The European startup-investor platform</p>

                      <p style="margin:0 0 16px;font-size:15px;color:#3f3f46;">
                        You've been invited to join StartGrid as a <strong>${roleLabel}</strong>.
                      </p>
                      <p style="margin:0 0 28px;font-size:14px;color:#71717a;">
                        Click the button below to set up your account. This invitation is unique to you.
                      </p>

                      <a href="${inviteUrl}"
                         style="display:inline-block;background:#18181b;color:#ffffff;padding:11px 24px;border-radius:6px;text-decoration:none;font-size:14px;font-weight:500;">
                        Accept invitation →
                      </a>

                      <p style="margin:28px 0 0;font-size:12px;color:#a1a1aa;">
                        Or copy this link into your browser:<br>
                        <span style="color:#52525b;">${inviteUrl}</span>
                      </p>
                      <p style="margin:16px 0 0;font-size:12px;color:#a1a1aa;">
                        If you didn't expect this invitation, you can safely ignore this email.
                      </p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </body>
      </html>
    `,
  });

  if (emailError) {
    return NextResponse.json(
      { error: `Failed to send invitation email: ${emailError.message}` },
      { status: 500 }
    );
  }

  return NextResponse.json({ success: true });
}
