"use client";

import { useState } from "react";
import { generateInvestmentBrief, type InvestmentBrief } from "@/app/actions/investment-brief";

interface Props {
  startupId: string;
  companyName: string;
}

const SECTIONS: { key: keyof Omit<InvestmentBrief, "generatedAt">; label: string; emoji: string }[] = [
  { key: "companyOverview",    label: "Company Overview",     emoji: "🏢" },
  { key: "marketOpportunity",  label: "Market Opportunity",   emoji: "📈" },
  { key: "teamStrengths",      label: "Team Strengths",       emoji: "👥" },
  { key: "keyRisks",           label: "Key Risks",            emoji: "⚠️" },
  { key: "investmentThesis",   label: "Investment Thesis",    emoji: "💡" },
];

export default function AIBriefButton({ startupId, companyName }: Props) {
  const [open, setOpen] = useState(false);
  const [brief, setBrief] = useState<InvestmentBrief | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleOpen() {
    setOpen(true);
    if (brief) return;
    setLoading(true);
    setError(null);
    const result = await generateInvestmentBrief(startupId);
    setLoading(false);
    if (result.error) { setError(result.error); return; }
    if (result.brief) setBrief(result.brief);
  }

  function handlePrint() {
    const win = window.open("", "_blank");
    if (!win || !brief) return;
    const html = `<!DOCTYPE html><html><head><title>Investment Brief – ${companyName}</title>
    <style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;color:#0F172A}h1{font-size:22px}h2{font-size:15px;margin-top:24px;border-bottom:1px solid #E2E8F0;padding-bottom:6px}p{line-height:1.7;font-size:14px;color:#334155}footer{margin-top:40px;font-size:11px;color:#94A3B8}</style>
    </head><body>
    <h1>Investment Brief – ${companyName}</h1>
    ${SECTIONS.map(s => `<h2>${s.emoji} ${s.label}</h2><p>${brief[s.key]}</p>`).join("")}
    <footer>Generated by StartGrid AI · ${new Date(brief.generatedAt).toLocaleDateString()}</footer>
    </body></html>`;
    win.document.write(html);
    win.document.close();
    win.print();
  }

  return (
    <>
      <button type="button" onClick={handleOpen} style={{
        padding: "9px 18px", borderRadius: 9,
        background: "linear-gradient(135deg, #0F172A, #1E3A5F)",
        border: "none", color: "white", fontSize: 13, fontWeight: 600,
        cursor: "pointer", display: "flex", alignItems: "center", gap: 7,
      }}>
        ✦ AI Investment Brief
      </button>

      {open && (
        <div style={{
          position: "fixed", inset: 0, zIndex: 200,
          backgroundColor: "rgba(0,0,0,0.5)",
          display: "flex", alignItems: "center", justifyContent: "center",
          padding: 20,
        }} onClick={e => { if (e.target === e.currentTarget) setOpen(false); }}>
          <div style={{
            backgroundColor: "white", borderRadius: 16,
            width: "100%", maxWidth: 620, maxHeight: "85vh",
            overflow: "hidden", display: "flex", flexDirection: "column",
            boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
          }}>
            {/* Header */}
            <div style={{
              padding: "20px 24px", borderBottom: "0.5px solid #E2E8F0",
              display: "flex", alignItems: "center", justifyContent: "space-between",
              background: "linear-gradient(135deg, #0F172A, #1E3A5F)",
            }}>
              <div>
                <p style={{ margin: 0, fontSize: 11, fontWeight: 600, color: "#94A3B8", textTransform: "uppercase", letterSpacing: "0.06em" }}>AI-Powered</p>
                <p style={{ margin: "2px 0 0", fontSize: 16, fontWeight: 700, color: "white" }}>Investment Brief — {companyName}</p>
              </div>
              <button type="button" onClick={() => setOpen(false)} style={{
                background: "rgba(255,255,255,0.1)", border: "none", color: "white",
                width: 30, height: 30, borderRadius: "50%", cursor: "pointer",
                fontSize: 16, display: "flex", alignItems: "center", justifyContent: "center",
              }}>×</button>
            </div>

            {/* Body */}
            <div style={{ overflowY: "auto", flex: 1, padding: "24px" }}>
              {loading && (
                <div style={{ textAlign: "center", padding: "48px 0" }}>
                  <p style={{ fontSize: 28, margin: "0 0 12px" }}>✦</p>
                  <p style={{ fontSize: 14, fontWeight: 600, color: "#0F172A" }}>Generating brief…</p>
                  <p style={{ fontSize: 13, color: "#94A3B8", margin: "4px 0 0" }}>Analysing pitch data with Claude</p>
                </div>
              )}
              {error && (
                <div style={{ backgroundColor: "#FFF1F2", border: "0.5px solid #FECDD3", borderRadius: 8, padding: "14px 16px", color: "#E11D48", fontSize: 13 }}>
                  {error}
                </div>
              )}
              {brief && !loading && (
                <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
                  {SECTIONS.map(s => (
                    <div key={s.key} style={{
                      backgroundColor: "#F8FAFC", borderRadius: 10,
                      border: "0.5px solid #E2E8F0", padding: "16px 18px",
                    }}>
                      <p style={{ margin: "0 0 8px", fontSize: 12, fontWeight: 700, color: "#475569", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                        {s.emoji} {s.label}
                      </p>
                      <p style={{ margin: 0, fontSize: 13, color: "#334155", lineHeight: 1.65 }}>
                        {brief[s.key]}
                      </p>
                    </div>
                  ))}
                  <p style={{ margin: 0, fontSize: 11, color: "#94A3B8", textAlign: "right" }}>
                    Generated {new Date(brief.generatedAt).toLocaleDateString()} · Powered by Claude
                  </p>
                </div>
              )}
            </div>

            {/* Footer */}
            {brief && !loading && (
              <div style={{
                padding: "14px 24px", borderTop: "0.5px solid #E2E8F0",
                display: "flex", gap: 10, justifyContent: "flex-end",
              }}>
                <button type="button" onClick={() => { setBrief(null); handleOpen(); }} style={{
                  padding: "8px 14px", borderRadius: 8,
                  border: "0.5px solid #E2E8F0", backgroundColor: "white",
                  fontSize: 12, fontWeight: 600, color: "#475569", cursor: "pointer",
                }}>
                  Regenerate
                </button>
                <button type="button" onClick={handlePrint} style={{
                  padding: "8px 16px", borderRadius: 8,
                  background: "linear-gradient(135deg, #4F46E5, #7C3AED)",
                  border: "none", color: "white", fontSize: 12, fontWeight: 600,
                  cursor: "pointer",
                }}>
                  Download PDF
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
